name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publier la version sur le Marketplace (true/false)'
        required: false
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release (semantic-release)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running release (semantic-release) before packaging/publish"
          npm run release

      - name: Build extension
        run: npm run build:esbuild

      - name: Package extension
        run: npm run vsce:package

      - name: Publish to VS Code Marketplace
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true' }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: |
          echo "Publishing to Marketplace"
          npx @vscode/vsce publish --pat $VSCE_PAT

      - name: Release step (commented fallback)
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.publish != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Release step skipped (not a manual publish dispatch with publish=true)"
